# -*- coding: utf-8 -*-
"""Ex1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ao6CCY_QiZWRDKAEfyfgpk9Du1oBRcGP
"""

def somme_liste(liste):
  return sum(liste)
somme_liste([1, 2, 3, 4])