# -*- coding: utf-8 -*-
"""Ex10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ao6CCY_QiZWRDKAEfyfgpk9Du1oBRcGP
"""

def fusionner_dicts(dict1, dict2):
  fusion = {}
  for element in dict1:
    fusion[element] = 1
  for element in dict2:
    if element in dict1:
      fusion[element] += 1
    else:
      fusion [element] = 1
  return fusion
dict1={'Ahmed','Brahim','Fati','Imane' }
dict2={'Mohammed','Brahim','Hamid','Imane'}
fusionner_dicts(dict1, dict2)