# -*- coding: utf-8 -*-
"""Ex2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ao6CCY_QiZWRDKAEfyfgpk9Du1oBRcGP
"""

def max_tuple(t):
  return max(t)
max_tuple((1, 2, 3, 2, 4, 1))