# -*- coding: utf-8 -*-
"""Ex3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ao6CCY_QiZWRDKAEfyfgpk9Du1oBRcGP
"""

def intersection(ensemble1, ensemble2):
  return ensemble1 & ensemble2
intersection({1, 2, 3},{2, 3, 4})