# -*- coding: utf-8 -*-
"""Ex6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ao6CCY_QiZWRDKAEfyfgpk9Du1oBRcGP
"""

carre = lambda n: n**2
print(carre(5))