# -*- coding: utf-8 -*-
"""Ex7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ao6CCY_QiZWRDKAEfyfgpk9Du1oBRcGP
"""

def salutation(nom, message="Bonjour"):
  return message + " " + nom
salutation("Ahmed")