# -*- coding: utf-8 -*-
"""Ex8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ao6CCY_QiZWRDKAEfyfgpk9Du1oBRcGP
"""

def somme_varargs(*args):
  return sum(args)
somme_varargs(1, 2, 3, 4)