# -*- coding: utf-8 -*-
"""EX1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1etZll9LYgO5uf2LaS6ZevZOIDguhio8k
"""

class chien:
  def __init__(self,nom,race,age):
    self.nom=nom
    self.race=race
    self.age=age
  def aboyer(self):
    return "Woof!"
chien1=chien("rex","pitbull",3)
chien1.aboyer()