# -*- coding: utf-8 -*-
"""EX2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1etZll9LYgO5uf2LaS6ZevZOIDguhio8k
"""

class voiture:
  def __init__(self,marque,modele,annee):
    self.marque=marque
    self.modele=modele
    self.annee=annee
  def afficherInfo(self):
    print(f'{self.marque, self.modele, self.annee}')
dadCar = voiture("opel","corsa",2011)
dadCar.afficherInfo()