# -*- coding: utf-8 -*-
"""EX2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1etZll9LYgO5uf2LaS6ZevZOIDguhio8k
"""

class compteBancaire:
  def __init__(self,titulaire,solde):
    self.titulaire= titulaire
    self.solde = solde
  def deposer(self,montant):
    self.solde += montant
  def retirer(self,montant):
    if self.solde > 0 and self.solde >= montant:
      self.solde -= montant
    else:
      return "solde insuffisant"
  def afficher_solde(self):
    return self.solde
client1=compteBancaire("Ahmed MHB",3000)
client1.retirer(4000)
client1.retirer(1000)
client1.deposer(2000)
client1.afficher_solde()