# -*- coding: utf-8 -*-
"""EX4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1etZll9LYgO5uf2LaS6ZevZOIDguhio8k
"""

class person:
  def __init__(self,nom,prenom,age):
    self.nom=nom
    self.prenom=prenom
    self.age=age
  def se_presenter(self):
    print(f"je suis {self.nom} {self.prenom}, j'ai {self.age} ans")
class etudiant(person):
  def __init__(self,nom,prenom,age,matricule):
    super().__init__(nom,prenom,age)
    self.matricule=matricule
  def etudier(self):
    print( self.matricule)
etudiant1= etudiant("Mouhib","Ahmed",21,"K13333776")
etudiant1.se_presenter()
etudiant1.etudier()