# -*- coding: utf-8 -*-
"""EX4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1etZll9LYgO5uf2LaS6ZevZOIDguhio8k
"""

class rectangle:
  def __init__(self,longueur,hauteur):
    self.longueur=longueur
    self.hauteur=hauteur
  def calculer_surface(self):
    print(self.longueur*self.hauteur)
  def calculer_perimetre(self):
    print(2*(self.longueur+self.hauteur))
rectangle1=rectangle(4,5)
rectangle1.calculer_surface()
rectangle1.calculer_perimetre()