# -*- coding: utf-8 -*-
"""EX4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1etZll9LYgO5uf2LaS6ZevZOIDguhio8k
"""

class livre:
  def __init__(self,titre,auteur,annee_publication):
    self.titre=titre
    self.auteur=auteur
    self.annee_publication=annee_publication
class bibliotheque(livre):
  def __init__(self, titre, auteur, annee_publication):
    super().__init__(titre, auteur, annee_publication)
  livres=[]
  def ajouter_livre(self):
    self.livres.append(self.titre)
  def afficher_livres(self):
    print(self.livres)
livre1=bibliotheque("la boite a merveille","sidi mohammed",1900)
livre1.ajouter_livre()
livre1.afficher_livres()